[package]
name = "dd"
version = "0.2.0"
authors = ["Hiroyuki Okamura <okamu@hiroshima-u.ac.jp>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
wyhash = "0.5.0"

[[bench]]
name = "bench_bdd"
harness = false

[[bench]]
name = "bench_mdd"
harness = false

[[bench]]
name = "bench_evmdd"
harness = false

[[bench]]
name = "bench_ft1"
harness = false

[[bench]]
name = "bench_ft2"
harness = false

[[bench]]
name = "bench_minsol"
harness = false
