[package]
name = "dd"
version = "0.1.0"
authors = ["Hiroyuki Okamura <okamu@hiroshima-u.ac.jp>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.11"
num-traits = "0.2"

[[bench]]
name = "bench_bdd"
harness = false

[[bench]]
name = "bench_mdd"
harness = false

[[bench]]
name = "bench_evmdd"
harness = false
