[package]
name = "mss"
version = "0.3.3"
authors = ["Hiroyuki Okamura <okamu@hiroshima-u.ac.jp>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mddcore = { path = "../mddcore" }

